name: Test CI/CD workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Install pre-requisites
        run: |
          sudo apt update
          sudo apt install gcc
          sudo apt install libgtest-dev
          sudo apt install libgmock-dev
      
      - name: Build C code
        run: |
          mkdir build
          cd build
          cp ../source/*.cpp .
          g++ -c allocate_memory.cpp
          g++ -o tester gtest_fixture01.cpp -lgmock -lgtest
      - name: Run Google mock test
        run: |
          ./tester
          
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run Google mock test
        run: |
          cd build
          ./tester
